version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/dist:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: lilscary
      DB_PASSWORD: root
      DB_NAME: lilscary
      DB_SCHEMA: lilscary

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: lilscary
      POSTGRES_PASSWORD: root
      POSTGRES_DB: lilscary
      POSTGRES_SCHEMA: lilscary
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
